"ADAM David Alan Martin's updated vimrc
"source ~/.vim/default.vim

"setf oopcpp

source ~/.vim/vimrc.colors

source ~/.vim/vimrc.globalprefs


source ~/.vim/vimrc.defkeymaps


source ~/.vim/vimrc.keymaps

source ~/.vim/vimrc.functions

source ~/.vim/vimrc.fileprefs
source ~/.vim/vimrc.syntaxcolors
source ~/.vim/vimrc.statusline

"compiler msvc
"set makeprg=wmake
"set errorformat=\ %#%f(%l\\\,%c):\ %m
