"ADAM David Alan Martin's updated vimrc
"source ~/.vim/default.vim

let g:netrw_special_syntax=1
set nofoldenable
syntax on

"The adam color scheme has both syntax colors and adam colorscheme now.
"This fixes the longstanding xterm-256color issues I've had.
colors adam


source ~/.vim/vimrc.globalprefs


source ~/.vim/vimrc.defkeymaps


source ~/.vim/vimrc.keymaps

source ~/.vim/vimrc.functions

source ~/.vim/vimrc.fileprefs
source ~/.vim/vimrc.statusline

set shell=/bin/tcsh
